library(astsa)
df <- as.data.frame(econ5)
attach(df)
# use smoothing
plot(unemp)
# moving average
library(smooth)
md<-sma(unemp,h=10,order=5)
summary(md)
forecast(md)
plot(forecast(md))
md<-sma(unemp,h=10,order=10)
summary(md)
forecast(md)
plot(forecast(md))
md<-sma(unemp,h=10,order=30)
summary(md)
forecast(md)
plot(forecast(md))
# NW, local linear
library(np)
xax<-seq(1:length(unemp))
plot(xax,unemp)
bwnw <- npregbw(unemp~xax,regtype="lc",bwmethod="cv.aic")
bwll <- npregbw(unemp~xax,regtype="ll",bwmethod="cv.aic")
nnw <- npreg(bwnw,residuals=T)
nll <- npreg(bwll,residuals=T)
plot(xax,unemp,col="grey")
lines(nnw$mean,col="red",lwd=2)
plot(xax,unemp,col="grey")
lines(nll$mean,col="blue",lwd=2)
# forecast
flen<-10
forecast <- seq(length(unemp)+1,length(unemp)+flen)
predll<-predict(nll, newdata=data.frame(xax=forecast))
prednw<-predict(nnw, newdata=data.frame(xax=forecast))
plot(c(unemp,prednw),col="white")
points(unemp,col="grey")
lines(c(unemp,prednw),col="red",lwd=2)
lines(c(unemp,predll),col="blue",lwd=2)
